require "capachrome/version"
require "capachrome/capabilities"
require "capachrome/profile"
require "capachrome/bridge"
require "capachrome/bridge_helper"
require "capachrome/capachrome_bridge"
require "capachrome/commands"
require "capachrome/json_helper"
require "capachrome/navigation"
require "capachrome/platform"
require "capachrome/profile_helper"
require "capachrome/response"
require "capachrome/search_context"
require "capachrome/server_error"
require "capachrome/service"
require "capachrome/socket_poller"
require "capachrome/takes_screenshot"
require "capachrome/has_input_devices"
require "capachrome/version"
require "capachrome/web_driver"
require "capybara/capachrome/driver"

module Capachrome
  # Your code goes here...
end
